---
layout: cv
title: Ethan Glenn CV
---

[Contact Me](https://eglenn.dev/contact)

## Education

**Bachelor of Science in Computer Science**        January 2023 - April 2026
Brigham Young University - Idaho        Rexburg, ID

* Emphasis in Machine Learning. Certificate in Full-Stack Web Development.
* GPA: 3.96.

## Skills

* **Web Development:** TypeScript, Next.js., React, JavaScript, HTML, CSS/SCSS
* **Data Analytics:** Python, R, SQL
* **Cloud:** Firebase, Render, Vercel

## Experience

**Team Lead & Web Developer**        July 2024 - Present
Brigham Young University - Idaho        Rexburg, ID

* Created a full-stack web app in Next.js with TypeScript for managing 3D print requests from library patrons. Used a Firebase NoSQL database, and Render.com for hosting.
* Lead developer for implementing new features and pages on library website.
* Implemented training solutions and documentation for library website to work with UI developers, University IT department for compliance, and library administration.

**Applied Calculus for Data Analytics Teaching Assistant**        April 2024 - Present
Department of Mathematics at Brigham Young University - Idaho        Rexburg, ID

* Held weekly office hours to assist students with understanding and applying calculus concepts to weekly data analysis programming projects in R.
* Offered tutoring support to multiple class sections to help with calculus concepts and the R programming language.

**Lab Technician & Front-End Developer**        June 2023 - July 2024
Brigham Young University - Idaho        Rexburg, ID

* Collaborated on a team to remodel the University Library website by transitioning from Bootstrap to Vanilla JS, utilizing HTML, CSS, and JS, while also integrating third-party APIs. In doing so reducing Largest Contentful Paint by 32%.
* Maintained a 3D printing maker lab designed to support over 1,200 students and faculty each month.
* Taught quarterly 3D printing and programming workshops for students.

## Projects

* 1st place winner of BYU-I-Hack 2024. Created a neighborhood watch app that won first place at the MLH sponsored hackathon.
* Created a full-stack web app for managing 3D print requests from students at BYU-Idaho.
* Utilized natural language processing in Python spaCy library to find similarities and patterns in large prices of text.
* Developed a website to summarize articles and documents using generative artificial intelligence in Python, HTML and JavaScript. 